---
abstract: 'Diagnostic delegation'
author:
  - 'Paul Liebert <paull@peak.org>'
build_requires:
  English: 0
  File::Basename: 0
  File::Spec::Functions: 0
  Moose: 0
  Pod::Coverage: 0.18
  Test::Exception: 0
  Test::More: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
  YAML::XS: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Proxy
no_index:
  directory:
    - t
    - inc
requires:
  Config: 0
  Cwd: 0
  English: 0
  Moose: 0
  Pod::Usage: 0
  Readonly: 0
  Sub::Name: 0
  YAML::XS: 0
  overload: 0
  perl: 5.010000
version: 0.11
